//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Package_Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string UseDiscordInstance {
            get {
                return ((string)(this["UseDiscordInstance"]));
            }
            set {
                this["UseDiscordInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchExcludeGuilds {
            get {
                return ((bool)(this["SearchExcludeGuilds"]));
            }
            set {
                this["SearchExcludeGuilds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchExcludeDMs {
            get {
                return ((bool)(this["SearchExcludeDMs"]));
            }
            set {
                this["SearchExcludeDMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchExcludeGDMs {
            get {
                return ((bool)(this["SearchExcludeGDMs"]));
            }
            set {
                this["SearchExcludeGDMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SearchExcludeIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchExcludeIDs"]));
            }
            set {
                this["SearchExcludeIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exact")]
        public string SearchMode {
            get {
                return ((string)(this["SearchMode"]));
            }
            set {
                this["SearchMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DeletedMessageIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeletedMessageIDs"]));
            }
            set {
                this["DeletedMessageIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SearchWhitelistIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchWhitelistIDs"]));
            }
            set {
                this["SearchWhitelistIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchBeforeEnabled {
            get {
                return ((bool)(this["SearchBeforeEnabled"]));
            }
            set {
                this["SearchBeforeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-01-01")]
        public global::System.DateTime SearchBeforeDate {
            get {
                return ((global::System.DateTime)(this["SearchBeforeDate"]));
            }
            set {
                this["SearchBeforeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchAfterEnabled {
            get {
                return ((bool)(this["SearchAfterEnabled"]));
            }
            set {
                this["SearchAfterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-01-01")]
        public global::System.DateTime SearchAfterDate {
            get {
                return ((global::System.DateTime)(this["SearchAfterDate"]));
            }
            set {
                this["SearchAfterDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCaseSensitive {
            get {
                return ((bool)(this["SearchCaseSensitive"]));
            }
            set {
                this["SearchCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("desc")]
        public string SortMode {
            get {
                return ((string)(this["SortMode"]));
            }
            set {
                this["SortMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchHasImage {
            get {
                return ((bool)(this["SearchHasImage"]));
            }
            set {
                this["SearchHasImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchHasFile {
            get {
                return ((bool)(this["SearchHasFile"]));
            }
            set {
                this["SearchHasFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchHasVideo {
            get {
                return ((bool)(this["SearchHasVideo"]));
            }
            set {
                this["SearchHasVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ResolvedDeletedUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResolvedDeletedUsers"]));
            }
            set {
                this["ResolvedDeletedUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
    }
}
